### ISSUE TITLE
How to apply this algorithm to my own dataset

### ISSUE THREAD

**Issue by Niloiv111** [Jianxff/pysrt3d#1]
Hi, thanks for sharing this.
I just wonder how to apply this algorithm to my own datasets, since when I tried to do this an error occurred:
Finish generating model Cup
n_histogram_bins_cubed_32768
Histograms could not be initialised for modality Cup
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    tracker.update(image=image_rgb)
RuntimeError: Could not start region modalities

By the way,  I changed the model_path and K. I'm looking forward to your reply!

**Comment by Jianxff** [comment]
Hi,
The error is most likely caused by a wrong initial pose. The algorithm is for object tracking only, so you have to set a valid initial pose at [this line](https://github.com/Jianxff/pysrt3d/blob/05a3a525ff02117cfe57a3f81a76de00d0284282/example/demo.py#L42). You can also define the initial pose (4 by 4 matrix, `meter` as unit) from numpy array instead of from the text file.

Btw, the object with the initial pose must be seen under camera coordinate, neither too close nor too far.

**Comment by Niloiv111** [comment]
Thanks for your reply.
I've changed the pose.txt already and I believe the pose estimation is accurate, but it still can't work.

**Comment by Jianxff** [comment]
Hi,
It should be noted that the pose matrix must under opencv coordinate, in which way the `z` value must be positive to make the model visible.

If you still have the problem, you can share your model file and pose file and I'll test it on my device.

**Comment by Niloiv111** [comment]
I think the initial pose matrix is correct. And I find another problem that there is no .meta file for my .obj mesh file. Does it matter?

**Comment by Niloiv111** [comment]
You can see my code in [https://pan.baidu.com/s/1qcVXh3p-elP7WRsg5e6UrQ?pwd=tg8a](url)

**Comment by Jianxff** [comment]
Hi,
You should pay attention to the arg `unit_in_meter` for `pysrt3d.Model`. Your model is made under meter so it should be set to 1.
I try that on my device and it works well. You can check my code as follows:
![image](https://github.com/user-attachments/assets/5712c7e9-cc8b-40a4-9b8c-26955053b82c)

**Comment by Niloiv111** [comment]
OOPS I didn't pay attention to it! And I fix it now. Thanks for your help!
